export default {
  description: 'testing again....',
  owner: 'norbert_csaba_herczeg',
  share: true,
  id: '5bd736bc9daec2000132c7d3',
  name: 'cumulx',
  content_parameters: {
    type: 'trends_chart',
    gadget: 'cumulative',
    content_fields: [
      'statistics$executions$failed',
      'statistics$executions$skipped',
      'statistics$executions$passed',
      'statistics$defects$product_bug$total',
      'statistics$defects$automation_bug$total',
      'statistics$defects$system_issue$total',
      'statistics$defects$no_defect$total',
      'statistics$defects$to_investigate$total',
    ],
    itemsCount: 10,
    widgetOptions: {
      filterName: ['DEMO_FILTER#_ncst'],
      prefix: ['prefx'],
    },
  },
  filter_id: '5bb34304027439000197a054',
  content: {
    result: [
      {
        id: 'test1',
        values: {
          statistics$executions$passed: '1101',
          statistics$defects$automation_bug$AB001: '176',
          statistics$defects$no_defect$ND001: '0',
          statistics$executions$skipped: '275',
          statistics$executions$failed: '496',
          statistics$executions$total: '1872',
          statistics$defects$to_investigate$TI001: '347',
          statistics$defects$system_issue$SI001: '124',
          statistics$defects$product_bug$PB001: '228',
        },
      },
      {
        id: 'prefx:test2',
        values: {
          statistics$executions$passed: '54',
          statistics$defects$automation_bug$AB001: '0',
          statistics$defects$no_defect$ND001: '0',
          statistics$executions$skipped: '0',
          statistics$executions$failed: '966',
          statistics$executions$total: '124',
          statistics$defects$to_investigate$TI001: '951',
          statistics$defects$system_issue$SI001: '785',
          statistics$defects$product_bug$PB001: '36',
        },
      },
      {
        id: 'prefx:test3',
        values: {
          statistics$executions$passed: '111',
          statistics$defects$automation_bug$AB001: '94',
          statistics$defects$no_defect$ND001: '850',
          statistics$executions$skipped: '144',
          statistics$executions$failed: '631',
          statistics$executions$total: '812',
          statistics$defects$to_investigate$TI001: '44',
          statistics$defects$system_issue$SI001: '88',
          statistics$defects$product_bug$PB001: '734',
        },
      },
    ],
  },
};
